#!/bin/bash


# generieke aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias cp="cp -i" # Confirm before overwriting something
alias df='df -h' # Human-readable sizes
alias free='free -m' # Show sizes in MB
alias ..='cd ..'
alias vi='nvim'
alias slf='sudo lf'
alias fm='vifm'
alias mi='micro'
alias please='sudo'
alias cdh="cd ~"
alias cdc="cd ~/.config"

# git 
alias gst='git status'
alias ga="git add"
alias gp="git push"
alias gc="git commit"
alias gs="git status"
alias gu="git add -u"
alias gunstage="git restore --staged ."
alias gl="git log --graph --all --pretty=format:'%Cred%h %Cgreen%cd%C(yellow)%d%Creset %s %C(bold blue)<%an>%Creset' --abbrev-commit --date=format:'%d%b%y %H:%M'"
#alias gl="git log --graph --all --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cd) %C(bold blue)<%an>%Creset' --abbrev-commit --date=format:'%d%b%y %H:%M'"
alias gl2="git log --all --decorate --oneline --graph"
alias gl3="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cs) %C(bold blue)<%an>%Creset' --abbrev-commit"
alias glt="git ls-tree --full-tree -r --name-only HEAD |fzf"

alias cclip='xclip -selection clipboard'
alias pclip='xclip -o -selection clipboard'



if [[ $(cat /etc/issue) =~ "Ubuntu" ]]; then
 	echo "Ubuntu detected, settings applied."
   echo " "
   alias update='sudo apt update'
else
 	echo "Arch detected, settings applied."
   echo " "
   alias update='sudo pacman -Syu'
fi

# dot management
# %cd = respecteer date format as stated in --date=format
# dot is defined in ~/.local/bin
dot config --local status.showUntrackedFiles no
alias dotl="dot log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cd) %C(bold blue)<%an>%Creset' --abbrev-commit --date=format:'%d%b%y %H:%M'"
alias dots='dot status -s -b'
alias dota='dot add'
alias dotlt='dot ls-tree --full-tree -r --name-only HEAD |fzf'
alias dotc='dot commit'
alias dotp='dot pull'
alias dotu='dot add -u'

