#!/bin/sh

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi

## Alias section
alias cp="cp -i"                                                # Confirm before overwriting something
alias df='df -h'                                                # Human-readable sizes
alias free='free -m'                                            # Show sizes in MB
alias gitu='git add . && git commit && git push'
alias ls='ls --color=always --group-directories-first'
alias l='ls --color=always -A --group-directories-first'
alias la='ls -liAFh --group-directories-first --color=always'
alias ll='ls -liFh --group-directories-first --color=always'
alias gst='git status'
alias pac='sudo pacman'
alias vi='nvim'
alias fm='vifm'
alias mi='micro'
alias please='sudo'
#alias gh="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
alias gh="git log --graph --all --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%ci)' --abbrev-commit"
alias gh2="git log --all --decorate --oneline --graph"
alias gh3="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cs) %C(bold blue)<%an>%Creset' --abbrev-commit"
alias gls="git ls-tree --full-tree -r --name-only HEAD |fzf"
alias cdh="cd ~"
alias cdc="cd ~/.config"
#alias mc=". /usr/share/mc/bin/mc-wrapper.sh"
alias update='sudo pacman -Syyu'
#Cleanup orphaned packages
alias cleanup='sudo pacman -Rns $(pacman -Qtdq)'


# ----=== Managing dotfiles ===----
git --git-dir=$HOME/.local/share/dotfiles/ --work-tree=$HOME config --local status.showUntrackedFiles no
# dotl=log   dots=status  dotlt=list tree
alias dotl='dot log --graph --pretty=format:"%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cs) %C(bold blue)<%an>%Creset" --abbrev-commit'
alias dots='dot status'
alias dotlt='dot ls-tree --full-tree -r --name-only HEAD |fzf'
alias dotcom='dot commit'

#get the error messages from journalctl
alias jctl="journalctl -p 3 -xb"

export EDITOR="/usr/bin/nvim"
#export EDITOR="/usr/bin/micro"

#nadat ranger --config-copy=all aangeven dat ie niet meer de default eerst moet laden
#export RANGER_LOAD_DEFAULT_RC=FALSE

#nnn config
export NNN_BMS='h:~/;c:~/.config/;d:~/Downloads/;e:/etc/;m:~/mydot;u:/usr/share'
export NNN_PLUG='c:fzcd;f:fzhist;h:hexview;i:imgview;o:fzopen;m:nmount;x:_chmod +x $nnn;S:suedit;u:uidgid'
export NNN_FCOLORS='c1e2272e006033f7c6d6abc4'
export NNN_COLORS='1267'
export NNN_FIFO=/tmp/nnn.fifo
export NNN_OPENER=/usr/share/nnn/plugins/nuke
export CUR_CTX=1

n ()
{
    # Block nesting of nnn in subshells
    if [ -n $NNNLVL ] && [ "${NNNLVL:-0}" -ge 1 ]; then
        echo "nnn is already running"
        return
    fi

    # The default behaviour is to cd on quit (nnn checks if NNN_TMPFILE is set)
    # To cd on quit only on ^G, remove the "export" as in:
    #     NNN_TMPFILE="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.lastd"
    # NOTE: NNN_TMPFILE is fixed, should not be modified
    export NNN_TMPFILE="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.lastd"

    # Unmask ^Q (, ^V etc.) (if required, see `stty -a`) to Quit nnn
    # stty start undef
    # stty stop undef
    # stty lwrap undef
    # stty lnext undef

    nnn -aceRH "$@"

    if [ -f "$NNN_TMPFILE" ]; then
            . "$NNN_TMPFILE"
            rm -f "$NNN_TMPFILE" > /dev/null
    fi
}
# USE LF TO SWITCH DIRECTORIES AND BIND IT TO CTRL-O
lfcd () {
    tmp="$(mktemp)"
    lf -last-dir-path="$tmp" "$@"
    if [ -f "$tmp" ]; then
        dir="$(cat "$tmp")"
        rm -f "$tmp"
        [ -d "$dir" ] && [ "$dir" != "$(pwd)" ] && cd "$dir"
    fi
}
bindkey -s '^o' 'lfcd\n'
