#!/bin/sh

function run {
  if ! pgrep $1 ;
  then
    $@&
  fi
}

_check() {
   command -v "$1" > /dev/null
}

#set resolution
# best to set in lightdm
#$HOME/.screenlayout/setres.h
#$HOME/.screenlayout/HP.sh
#xrandr --output Virtual-1 --mode 1920x1080
#xbacklight -d eDP-1 -set 100%
#xrandr --output eDP-1 --brightness 1.1

#Assign capslock key as an additional superkey
setxkbmap -option caps:super

#killall sxhdk and restart
pgrep -x sxhkd > /dev/null || sxhkd -c ~/.config/bspwm/sxhkd/sxhkdrc &

# automatisch gebruik picom config in .config/picom.picom.conf
# dit is de https://github.com/ibhagwan/picom versie met rounded corners
# wel blur uitzetten - trekt zware wissel
pgrep -x picom && pkill -x picom
picom --experimental-backends &


#Some ways to set your wallpaper besides variety or nitrogen
#feh --bg-fill $HOME/Pictures/citylife.jpg &
#wal -i $HOME/Downloads/jp-green.jpg &
nitrogen --restore &

xsetroot -cursor_name left_ptr &

#polybar
#pgrep -x polybar && pkill -x polybar
~/.config/polybar/launch.sh &


############################################################
# BSPWM configuration
############################################################
~/.config/bspwm/masterlayout.sh &
bspc config external_rules_command  ~/.config/bspwm/external_rules.sh

#bspc config border_radius       8
bspc config border_width         2
bspc config window_gap           5
bspc config top_padding          0
bspc config bottom_padding       0
bspc config left_padding         0
bspc config right_padding        0
bspc config single_monocle       true
bspc config click_to_focus       true
bspc config split_ratio          0.55
bspc config borderless_monocle   true
bspc config gapless_monocle      false
#bspc config focus_by_distance    true
bspc config focus_follows_pointer false
#bspc config history_aware_focus  true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true
bspc config removal_adjustment false

#BSPWM coloring
bspc config normal_border_color		"#4c566a"
bspc config active_border_color		"#fcd303"
bspc config focused_border_color		"#FFFFEE"
#bspc config focused_border_color	"#5e81ac"
bspc config presel_feedback_color	"#5e81ac"
#bspc config urgent_border_color 	"#dd2727"

#Single monitor
bspc monitor -d I II III IV V

#Dual monitor
#find out names with arandr or xrandr
#bspc monitor DP3-2 -d 〇 一 二 三 四 五 六
#bspc monitor eDP1 -d 七 八 九
#monitor on the left must start with 1
#bspc monitor eDP-1 -d 1 2 3
#bspc monitor HDMI-1 -d 4 5 6 7 8 9 0


#Fullscreen applications
#bspc rule -a inkscape state=fullscreen
#bspc rule -a Spotify state=fullscreen
#bspc rule -a Vlc state=fullscreen
#bspc rule -a VirtualBox Manager state=fullscreen
#bspc rule -a VirtualBox Machine state=fullscreen
#bspc rule -a Gimp state=fullscreen

#Floating applications
bspc rule -a Arandr state=floating
#bspc rule -a feh state=floating
#bspc rule -a mpv state=floating sticky=on
#bspc rule -a Font-manager state=floating
#bspc rule -a Galculator state=floating
#bspc rule -a Gpick state=floating sticky=on
#bspc rule -a Nitrogen state=floating
#bspc rule -a Oblogout state=floating
#bspc rule -a Pavucontrol state=floating sticky=on
#bspc rule -a Peek state=floating
#bspc rule -a rofi state=floating sticky=on
#bspc rule -a Skype state=floating
#bspc rule -a Stacer state=floating
#bspc rule -a Xfce4-appfinder state=floating sticky=on
#bspc rule -a Xfce4-terminal state=floating

#Tiled applications
#bspc rule -a Gnome-disks state=tiled
#bspc rule -a Xfce4-settings-manager state=tiled

#open applications on specific workspaces
bspc rule -a firefox desktop='^3' follow=on
#bspc rule -a Google-chrome desktop='^1' follow=on
#bspc rule -a Chromium desktop='^1'  follow=on
#bspc rule -a Subl3 desktop='^2' follow=on
#bspc rule -a Atom desktop='^2' follow=on
#bspc rule -a Steam desktop='^5'
#bspc rule -a vlc desktop='^6'  follow=on
#bspc rule -a mpv desktop='^6'  follow=on
#bspc rule -a Vivaldi-stable desktop='^6' follow=on
#bspc rule -a Vivaldi-snapshot desktop='^6' follow=on
#bspc rule -a Transmission-gtk desktop='^7' follow=on
#bspc rule -a Thunar desktop='^8' follow=on
#bspc rule -a discord desktop='^9' follow=on
#bspc rule -a Spotify desktop='^10' follow=on

#Spotify fix  --move desktop 10
#sleep 1
#wmctrl -r Spotify -t 10
#exit

#polybar hidden when fullscreen for vlc, youtube, mpv ...
#find out the name of your monitor with xrandr
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DP-1)
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI1)
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI2)

###External rules
##Pseudo automatic mode: always splits focused window when opening new window
#bspc config external_rules_command ~/.config/bspwm/scripts/pseudo_automatic_mode
##Adjust new window: splits biggest windows to keep windows about the same size
#bspc config external_rules_command ~/.config/bspwm/scripts/adjust-new-window
