theme = "heisenberg"

[editor]
line-number = "absolute"
mouse = true
true-color = true
scrolloff = 3
bufferline = "multiple"
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
";" = "command_mode"
"tab" = ":bn"
"A-w" = "rotate_view"

[keys.insert.j]
j = "normal_mode" # Maps `jj` to exit insert mode

